### ISSUE TITLE
mgart_test1 segfaulting

### ISSUE THREAD

**Issue by ArchangeGabriel** [CODARcode/MGARD#105]
While trying to build the project on Arch Linux, I got a segfault for the aforementioned test:
```
1/3 Test #1: mgard_test1 ......................***Exception: SegFault  0.31 sec
```
Not sure what could help you debug this, so just ask whatever you need. ;)

**Comment by qliu21** [comment]
I will look into this. My apologies that I have other deadlines at the moment. Therefore, it will take sometime (2 weeks).

Meanwhile, just out of curiosity, what applications do you need MGARD for? For all major HPC systems, we haven't tested
Arch Linux yet, since we don't have any systems using Arch Linux.

**Comment by qliu21** [comment]
Yeah, the MGARD API was recently changed, but ADIOS has not been updated yet. Therefore, I expect compile issues, which
I will fix soon. Thanks for letting us know.

**Comment by ben-e-whitney** [comment]
This segfault no longer occurs. The immediate cause is that we've stopped running tests from CMake. (We've added many more tests than we've deleted. Everything's now run with Catch2.) My guess is that the segfault was ultimately caused by interpreting a 513 × 513 dataset as a 513 × 513 × 1 dataset. I'm working on that issue now.
