### ISSUE TITLE
Calling decompress on a CompressedDataset crashes

### ISSUE THREAD

**Issue by kmorel** [CODARcode/MGARD#153]
It no longer works to call `mgard::decompress` on a `CompressedDataset<T,Real>` (that comes from `mgard::compress`). Typically you get a crash.

What think is happening is that `mgard::compress` now puts in a self-describing header. This header is ignored by the overload of `decompress` that takes a `CompressedDataset` (even though its buffer has that header). Consequently, parts of the header (like the signature and version numbers) are read as buffer sizes, and things go downhill from there.

**Comment by ben-e-whitney** [comment]
Your diagnosis is right, @kmorel. You shouldn't have to call `mgard::decompress(void const * const, const std::size_t)` now – calling `mgard::compress` followed by `mgard::decompress(const CompressedDataset &)` should still work. I assumed it still did because the tests in `tests/src/test_compress.hpp` still passed. However, in 6d138ed4a163195e334f42a327a997fbae41e9c8 the decompression call in those tests was changed to the new overload, so the regression wasn't caught. @qliu21, you should have added new tests rather than repurposing the existing ones. I will fix this after finishing the new serialization implementation.
